nome = str(input ("Digite seu nome completo: ")).strip()
div = nome.split ()
print ("1° Nome MAIUSCULO: {}".format(div[0].upper()))
print ("1° Nome minuscula: {}".format (div[0].lower()))
print ("1° Nome Quantidade de letras: {}".format (len(div[0])))
print ("Nome Completo MAIUSCULO: {}".format (nome.upper ()))
print ("Nome Completo minusculo: {}".format (nome.lower ()))
semesp = nome.replace (" ","")
print ("Quantidade de Letras: {}".format (len (semesp)))
