variavel = input ('Digite algo: ')
print ('O tipo da dessa variavel é: ',type(variavel))
print ('Só tem espaço? ',variavel.isspace())
print ('É um numero?', variavel.isnumeric())
print ('É só letras?', variavel.isalpha ())
print ('É letra e numero?', variavel.isalnum())
print ('Está em maiúscula? ',variavel.isupper())
print ('minúscula? ', variavel.islower ())
print ('Capitalizada?', variavel.istitle ())
